/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proyectoRentCar.archivos.Movimiento;

import com.proyectoRentCar.archivos.ManejoDeArchivo;
import com.proyectoRentCar.vistas.MenuPrincipal;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class RecepcionVehiculo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RecepcionVehiculo.class.getName());

         
    public RecepcionVehiculo() {
        initComponents();
        txtIdRecepcion.addActionListener(e -> btnBuscar.doClick());
           bloquearCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdRecepcion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIdMatricula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFechaRecepcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtObservacion = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lbEstado = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setText("ID Recepción");

        jLabel2.setText("Matricula ");

        jLabel3.setText("Fecha Recepción");

        jLabel4.setText("Obeservación");

        btnBuscar.setText("Buscar ");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnLimpiar.setText("Limpiar ");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtIdMatricula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtIdRecepcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFechaRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(47, 47, 47)
                                .addComponent(btnBuscar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnGuardar)
                        .addGap(58, 58, 58)
                        .addComponent(btnLimpiar)
                        .addGap(69, 69, 69)
                        .addComponent(btnVolver))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtFechaRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtObservacion, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnVolver))
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 480, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
                          String id = txtIdRecepcion.getText();

    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese ID Recepción");
        return;
    }

    ManejoDeArchivo ma = new ManejoDeArchivo();
    String datos[] = ma.BuscarDatos(id, new File("recepcionVehiculos.txt"));

    if (datos != null) {
        // 🔵 EXISTE → MODIFICANDO
        habilitarCampos();

        txtIdMatricula.setText(datos[1]);
        txtFechaRecepcion.setText(datos[2]);
        txtObservacion.setText(datos[3]);

        txtIdMatricula.setEditable(false); // ❌ NO modificar
                              String lineaOriginal = String.join(";", datos);
        lbEstado.setText("MODIFICANDO");
                              boolean lbEstadoB = true;

    } else {
        // 🟢 NO EXISTE → CREANDO
        habilitarCampos();

        txtIdMatricula.setText("");
        txtFechaRecepcion.setText("");
        txtObservacion.setText("");

        txtIdRecepcion.setText(id);

        lbEstado.setText("CREANDO");
          boolean lbEstadoB = false;
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
                            File archivo = new File("recepcionVehiculos.txt");

    String id = txtIdRecepcion.getText();
    String matricula = txtIdMatricula.getText();
    String fecha = txtFechaRecepcion.getText();
    String obs = txtObservacion.getText();

    // 🔴 VALIDAR CAMPOS
    if (id.isEmpty() || matricula.isEmpty() || fecha.isEmpty() || obs.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios");
        return;
    }

    ManejoDeArchivo ma = new ManejoDeArchivo();

    // 🔴 VALIDAR MATRÍCULA EXISTE
    String datosVeh[] = ma.BuscarDatos(matricula, new File("vehiculos.txt"));

    if (datosVeh == null) {
        JOptionPane.showMessageDialog(this, "La matrícula no existe");
        return;
    }

    // 🔴 VALIDAR RESERVA
    String datosReserva[] = ma.BuscarDatos(matricula, new File("reservas.txt"));

    if (datosReserva == null) {
        JOptionPane.showMessageDialog(this, "No existe reserva para esta matrícula");
        return;
    }

    String fechaEntrada = datosReserva[2];

    if (fecha.compareTo(fechaEntrada) < 0) {
        JOptionPane.showMessageDialog(this, "Fecha inválida");
        return;
    }

    String datos = id + ";" + matricula + ";" + fecha + ";" + obs;
        boolean lbEstadoB = false;

    if (lbEstadoB) {
         String lineaOriginal = null;
        ma.ModificarDatos(lineaOriginal, datos, archivo);
        JOptionPane.showMessageDialog(this, "Modificado correctamente");
    } else {
        ma.GuardarDatos(datos, archivo);
        JOptionPane.showMessageDialog(this, "Guardado correctamente");
    }

    // 🔥 ACTUALIZAR VEHÍCULO
    actualizarVehiculoDisponible(matricula);

    limpiarDatos();
    bloquearCampos();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
      limpiarDatos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
      new MenuPrincipal().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RecepcionVehiculo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lbEstado;
    private javax.swing.JTextField txtFechaRecepcion;
    private javax.swing.JTextField txtIdMatricula;
    private javax.swing.JTextField txtIdRecepcion;
    private javax.swing.JTextField txtObservacion;
    // End of variables declaration//GEN-END:variables

    private void bloquearCampos() {
    txtIdRecepcion.setEditable(true);
    txtIdMatricula.setEditable(false);
    txtFechaRecepcion.setEditable(false);
    txtObservacion.setEditable(false);
    btnGuardar.setEnabled(false);
    lbEstado.setEnabled(false);
    }

   public void habilitarCampos() {
    txtIdRecepcion.setEditable(false);
    txtIdMatricula.setEditable(true);
    txtFechaRecepcion.setEditable(true);
    txtObservacion.setEditable(true);
    btnGuardar.setEnabled(true);
    lbEstado.setEnabled(true);
}
 public void limpiarDatos() {
    txtIdRecepcion.setText("");
    txtIdMatricula.setText("");
    txtFechaRecepcion.setText("");
    txtObservacion.setText("");
    lbEstado.setText("");
}

    private void actualizarVehiculoDisponible(String matricula) {
    ManejoDeArchivo ma = new ManejoDeArchivo();
    File archivoVeh = new File("vehiculos.txt");

    String datosVeh[] = ma.BuscarDatos(matricula, archivoVeh);

    if (datosVeh == null) {
    } else {
        String lineaVieja = String.join(";", datosVeh);

        datosVeh[11] = "true"; // Disponible

        String lineaNueva = String.join(";", datosVeh);

        ma.ModificarDatos(lineaVieja, lineaNueva, archivoVeh);
        }
    }
}